### ISSUE TITLE
CI BOT 基本就绪了

### ISSUE THREAD

**Issue by wzshiming** [DaoCloud-OpenSource/ci-bot-playground#10]
/assign @jonyhy96 @Iceber @muma378 @kerthcet @kebe7jun

大佬们可以来试用一下, 提一波意见

**Comment by wzshiming** [comment]
这个 assign 好像只能对 member 用来着

**Comment by kebe7jun** [comment]
where are the docs?

**Comment by wzshiming** [comment]
> where are the docs?

@kebe7jun 
https://github.com/wzshiming/gh-ci-bot

**Comment by wzshiming** [comment]
https://github.com/DaoCloud-OpenSource/ci-bot-playground/blob/main/.github/workflows/ci-bot.yml#L16-L70

这里定义的权限 和 角色

**Comment by wzshiming** [comment]
kind/doc 这种需要提前创建来着

**Comment by kebe7jun** [comment]
还属于小项目，没必要把角色分这么细吧。hhh。

istio 到现在都还只有 maintainer 和 member。

**Comment by wzshiming** [comment]
是的, 只是先加了

**Comment by wzshiming** [comment]
这个仓库先权限都给所有人了先 https://github.com/DaoCloud-OpenSource/ci-bot-playground/pull/11

**Comment by wzshiming** [comment]
@jonyhy96
Add label help wanted to DaoCloud-OpenSource/ci-bot-playground#10
GraphQL error: API rate limit exceeded for user ID 95411464.

**Comment by wzshiming** [comment]
这个尴尬的一匹

**Comment by wzshiming** [comment]
> /merge 命令是不是可以换成 /approve 之类的比较好？/merge 表示直接合并，但有时候，可能存在需要多个人 approve 之后才合并好些？并增加一个自动合并的功能。

@kebe7jun
是的现在就写了单独的功能呢, 一些额外的策略我感觉也是有必要的

**Comment by jonyhy96** [comment]
两个lgtm就让robot自动合并?

**Comment by wzshiming** [comment]
和 k8s 一样 一个 lgtm + 一个 approve 也行啊

**Comment by wzshiming** [comment]
换了个 TOKEN , 个人账户的 API 调用的限制的次数好低

**Comment by wzshiming** [comment]
> jonyhy96

两个 lgtm 的 label 没办法加
